/*
* This file was generated by the Gradle 'init' task.
*
* This is a general purpose Gradle build.
* Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
*/
plugins {
  `build-scan`
  application
  kotlin("jvm") version "1.3.31"
}

repositories {
  mavenCentral()
}

application {
  mainClassName = "interview.InterviewKt"
}

tasks.withType<Test> {
  useJUnitPlatform()
  testLogging {
    events("passed", "skipped", "failed")
  }
}

dependencies {
  implementation(kotlin("stdlib"))
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines:0.19.2")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1")
  testImplementation("org.junit.jupiter:junit-jupiter:5.4.2")
  testImplementation(kotlin("test"))
}
